### ISSUE TITLE
Thanks and Minimize question

### ISSUE THREAD

**Issue by markstos** [illuzor/Play-Button-For-Google-Play-Music#1]
Hello,

Thank you for this project. I find it helpful. 

I'm wondering if it's possible to fix another issue with Google Music that affects Chrome OS. 

On Chrome OS, the keyboard shortcut "Alt -" is used to minimize a window. Unfortunately, "Google Music" also uses it mean "thumbs down song". I would simply like to disable that keyboard shortcut on Google Music. Can it be done?

**Comment by illuzor** [comment]
Hello.
This problem is not related to the extension.
